name: Bug Report
description: Signaler un bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug !

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug.
      placeholder: Décrivez le comportement inattendu...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire ce bug ?
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran.

  - type: dropdown
    id: device
    attributes:
      label: Type d'appareil
      options:
        - Mobile (Android)
        - Mobile (iOS)
        - Tablette
        - Desktop
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Navigateur
      placeholder: Chrome 120, Firefox 121, Safari 17...

  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Tout autre contexte utile.
